# -*- coding: utf-8 -*-
"""Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhV9BZcZElU-Wx6cueMFeDSKy6Z8E2RJ

# LogisiticRegression

#Step 1: Import Required Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""#Step 2: Load Dataset"""

data = pd.read_csv("Facebook live sellers.csv")

"""#Step 3: View Dataset"""

data.head()

"""#Step 4: Prepare Features (X) and Target (y)"""

X=data[['num_reactions', 'num_comments', 'num_shares', 'num_likes', 'num_loves', 'num_wows', 'num_hahas', 'num_sads', 'num_angrys']]

X.shape

y=data[['status_type']]

y.shape

"""#Step 5: Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state =0)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""#Step 6: Train Model"""

LR=LogisticRegression()

LR.fit(X_train, y_train)

y_pre = LR.predict(X_test)

accuracy = accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)

"""# **DecisionTreeClassifier**

#Step 1: Import Required Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

"""#Step 2: Load Dataset"""

data = pd.read_csv("Facebook live sellers.csv")

"""#Step 3: View Dataset"""

data.head()

"""#Step 4: Prepare Features (X) and Target (y)"""

X=data[['num_reactions', 'num_comments', 'num_shares', 'num_likes', 'num_loves', 'num_wows', 'num_hahas', 'num_sads', 'num_angrys']]

X.shape

y=data[['status_type']]

y.shape

"""#Step 5: Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =0)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""#Step 6: Train Model"""

DT=DecisionTreeClassifier()

DT.fit(X_train, y_train)

y_pre=DT.predict(X_test)

accuracy=accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)